project 'RNTokenizer.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RNTokenizer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTokenizer
  pod 'PaymentsSDK', '~> 1.0.7'

end
